require('aframe');
require('aframe-layout');
require('./asteroid-explosion-shader.js');
require('./asteroid-component.js');
require('./distance-limiter-component.js');
require('./throwingAsteroidsAtYouTest.js');
require('./laser-component.js');
require('./spawner-component.js');
require('./collider.js');
